[package]
name = "abci-shim"
version = "0.1.0"
authors = ["Reisen <reisen@morphism.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
