name:                tensor
version:             0.1.0.0
github:              "Reisen/tensor"
license:             BSD3
author:              "Reisen"
maintainer:          "reisen@morphism.org"
copyright:           "2019 Reisen"
description:         Please see the README on GitHub at <https://github.com/Reisen/tensor#readme>
extra-source-files:  []

dependencies:
  - base

executables:
  tensor:
    main:                Main.hs
    extra-lib-dirs:      ../abci-shim/target/debug
    extra-libraries:     abci_shim
    source-dirs:         .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - base58string
      - bytestring
      - criterion
      - cryptonite
      - lens
      - memory
      - protolude
      - text
